### PR TITLE
Add six

### PR DESCRIPTION
**Pull request by aras7**

### CODE REVIEW

**Comment by PeteAndersen** [comment]
Would appreciate accepting this pull request

**Comment by atombrella** [comment]
Why not use `django.utils.six` instead of introducing more third-party libraries? The interface is the same.

**Comment by ben-simmons** [comment]
I don't think the six.PY2 case is necessary, because Python 3 super() is backwards compatible with Python2 super(). You can use args for both, e.g. `super(Percentile, self)`.

**Comment by ben-simmons** [comment]
Thanks for merging this, @cndreisbach. Any chance you could roll this into a release and push to PyPI? I'd offer to do it, but I'm not familiar with the process and assume I'd need a private key for the project.

**Pull request merged**
